### PR TITLE
Fix v0.12.1 and below compatibility

### LINKED ISSUE #403: CCM 3.6.0 + Metallb 0.12.1 (configmap method) Not working
@enkelprifti98 reported that CCM fills the configmap but the metallb controller sees this issue:

```
{"caller":"level.go:63","configmap":"metallb-system/config","error":"could not parse config: yaml: unmarshal errors:\n  line 18: field name not found in type config.peer\n  line 35: field name not found in type config.peer\n  line 52: field name not found in type config.peer\n  line 69: field name not found in type config.peer\n  line 86: field name not found in type config.peer\n  line 103: field name not found in type config.peer","event":"configStale","level":"error","msg":"config (re)load failed, config marked stale","ts":"2023-04-12T14:52:30.650102522Z"}
```

### PR DESCRIPTION
**Pull request by cprivitere**
Added omitempty to the name field. 
Switch to the kubernetes managed yaml library
Use json struct tags instead of yaml struct tags as the k8s library doesn't work with yaml struct tags
Add additional tags for remaining fields, else they get named incorrectly in the configmap (it's case sensitive)
Bump go and k8s deps while i'm in here

Fixes #403

### CODE REVIEW

File: metal/loadbalancers/metallb/config.go [hunk 1]
```diff
@@ -28,46 +28,46 @@ import (
...
 }
 
 type AddressPool struct {
-	Protocol          Proto
-	Name              string
-	Addresses         []string
-	AvoidBuggyIPs     bool               `yaml:"avoid-buggy-ips"`
-	AutoAssign        *bool              `yaml:"auto-assign"`
-	BGPAdvertisements []BgpAdvertisement `yaml:"bgp-advertisements"`
+	Protocol          Proto              `json:"protocol"`
```
Comment (ctreatma) [inline metal/loadbalancers/metallb/config.go:61]: Were these missing struct tags causing errors somewhere?

File: metal/loadbalancers/metallb/config.go [hunk 2]
```diff
@@ -28,46 +28,46 @@ import (
...
+	Addresses         []string           `json:"addresses"`
+	AvoidBuggyIPs     bool               `json:"avoid-buggy-ips"`
+	AutoAssign        *bool              `json:"auto-assign"`
+	BGPAdvertisements []BgpAdvertisement `json:"bgp-advertisements"`
 }
 
 type BgpAdvertisement struct {
-	AggregationLength *int `yaml:"aggregation-length"`
+	AggregationLength *int `json:"aggregation-length"`
 	LocalPref         *uint32
```
Comment (ctreatma) [inline metal/loadbalancers/metallb/config.go:71]: These properties are also missing struct tags; are they not needed for these fields?

Comment (cprivitere) [reply metal/loadbalancers/metallb/config.go:71]: I only added tags to the fields that 0.12.1 wanted.

File: metal/loadbalancers/metallb/config.go (hunk 1 above)
Comment (cprivitere) [reply metal/loadbalancers/metallb/config.go:61]: Yes, the yaml library was importing them as a capital letter instead of lower case.

**Review by ctreatma — APPROVED** [review]
